### ISSUE TITLE
The box does not change the size according to the text

### ISSUE THREAD

**Issue by JoseEstradaC** [AlexSegen/toastmejs#1]
The box does not change the size according to the text, this causes the text to be cut
![089333e98f353a815cfb7b102fe030a9](https://user-images.githubusercontent.com/28443909/57192757-23232880-6f34-11e9-9a33-1d0e4847d1fe.png)

**Comment by AlexSegen** [comment]
Hello, thank you for comment. I just added new CSS rules to prevent this to happen. For aesthetic reasons, I want to set  max-width to the notifications. But long text or words will jump to next line and won't get cut.

Next version, I will release this fix. for now it will be on **dev branch.**

![image](https://user-images.githubusercontent.com/5666895/57229141-612b5580-6fe3-11e9-90af-568607521e1b.png)


Cheers!

**Comment by AlexSegen** [comment]
Fixed released @ v1.2.1
