### ISSUE TITLE
Dialog height broken

### ISSUE THREAD

**Issue by Razer2015** [AlexSegen/toastmejs#12]
Seems like these days the dialog heights are broken on most browsers (Chrome, FireFox, Opera, Edge (Chromium)).

![toastme_dialog](https://user-images.githubusercontent.com/10619845/129701517-4dd12efa-2524-407d-9214-60479790d513.png)

**Comment by AlexSegen** [comment]
Thank you for reporting this. It's now fixed in a new version.
