### ISSUE TITLE
Icons are not loading

### ISSUE THREAD

**Issue by badsmoke** [AlexSegen/toastmejs#2]
the icons do not load properly anymore, there is a "CORS" problem in the console. But when I download and embed the css the icons are still not loaded.

I already deleted the cache several times

![image](https://user-images.githubusercontent.com/24853712/68306171-53957c00-00a9-11ea-9e2f-01bcc874f20c.png)

**Comment by AlexSegen** [comment]
Hi @badsmoke. Please, forgive that I didn't reply before. I didn't realized about these issues sooner. I wanted to tell you that I just tested and tried to reproduce your problem without success. Please, try again with newest versions and tell me if it's working for you. Furthermore, if you could show me some of your code I could check it out.
