### ISSUE TITLE
toastme is not a constructor

### ISSUE THREAD

**Issue by sebastian-seg** [AlexSegen/toastmejs#5]
When trying to create a new instance of the toaster, It failes on excecution time. Showing up this message. Also, when you create the new toaster, you can not use
`const mytoast = new Toastme(config);`
Since it fails recovering such constructor (after all, we imported toastme, not Toastme), so, in order for the app to compile, you need to change this call to "new toastme(...", but then we get the excecution time error

As of now, it can not be used as intended

**Comment by AlexSegen** [comment]
If you import `toastme`,  it's enough to make all its methods work. For example,

`toastme.success('Hello');`

If you want to customize your notifications, you need to import the `Class` called `Toastme`  (with capitalized T). Then, you need to create a new instance from it. As you said, `const mytoast = new Toastme(config);`

Finally, use the just created instance.

`mytoast.success('hello');`
